USE Glassy
GO

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'Glass')
DROP TABLE Glass
GO

CREATE TABLE Glass (
	GlassId INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Title NVARCHAR (100) NOT NULL,
	Details NVARCHAR (400) NOT NULL,
	Price  DECIMAL (10,2) NOT NULL
)

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'Paper')
DROP TABLE Paper
GO

CREATE TABLE Paper (
	PaperId INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Title NVARCHAR (100) NOT NULL,
	Details NVARCHAR (400) NOT NULL,
	Price DECIMAL (10,2) NOT NULL
)

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'Coffee')
DROP TABLE Coffee
GO

CREATE TABLE Coffee (
	CoffeeId INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	Title NVARCHAR (100) NOT NULL,
	Details NVARCHAR (400) NOT NULL,
	Price DECIMAL (10,2) NOT NULL
)


